project_name: server_box_monitor
builds:
  - env: [CGO_ENABLED=0]
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "6"
      - "7"
    goos:
      - linux
      - windows
      - darwin
    ignore:
      - goos: windows
        goarch: arm
        goarm: 6
      - goos: windows
        goarch: arm
        goarm: 7
      - goos: darwin
        goarch: arm
        goarm: 6
      - goos: darwin
        goarch: arm
        goarm: 7
