//! Registry for host primitives that LLVM AOT may call through `lkrt`.
//!
//! This is metadata only. Full stdlib method bodies should live in LK stdlib
//! source or in compile-time constant evaluation, not as scattered LLVM matches.

#![allow(dead_code)]

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(in crate::llvm) enum NativeIntrinsicEffect {
    Pure,
    ReadsHost,
    WritesHost,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(in crate::llvm) enum NativeIntrinsicType {
    I64,
    F64,
    Ptr,
    StrPtr,
    Nil,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(in crate::llvm) struct NativeIntrinsic {
    pub module: &'static str,
    pub name: &'static str,
    pub symbol: &'static str,
    pub params: &'static [NativeIntrinsicType],
    pub result: NativeIntrinsicType,
    pub effect: NativeIntrinsicEffect,
}

pub(in crate::llvm) const NATIVE_INTRINSICS: &[NativeIntrinsic] = &[
    NativeIntrinsic {
        module: "lkrt",
        name: "abi_version",
        symbol: "lkrt_abi_version",
        params: &[],
        result: NativeIntrinsicType::I64,
        effect: NativeIntrinsicEffect::Pure,
    },
    NativeIntrinsic {
        module: "lkrt",
        name: "cleanup",
        symbol: "lkrt_cleanup",
        params: &[],
        result: NativeIntrinsicType::Nil,
        effect: NativeIntrinsicEffect::WritesHost,
    },
    NativeIntrinsic {
        module: "lkrt",
        name: "error_clear",
        symbol: "lkrt_error_clear",
        params: &[],
        result: NativeIntrinsicType::Nil,
        effect: NativeIntrinsicEffect::WritesHost,
    },
    NativeIntrinsic {
        module: "lkrt",
        name: "last_error",
        symbol: "lkrt_last_error",
        params: &[],
        result: NativeIntrinsicType::StrPtr,
        effect: NativeIntrinsicEffect::ReadsHost,
    },
    NativeIntrinsic {
        module: "lkrt",
        name: "string_free",
        symbol: "lkrt_string_free",
        params: &[NativeIntrinsicType::StrPtr],
        result: NativeIntrinsicType::Nil,
        effect: NativeIntrinsicEffect::WritesHost,
    },
    NativeIntrinsic {
        module: "socket",
        name: "addr",
        symbol: "lkrt_socket_addr",
        params: &[NativeIntrinsicType::StrPtr, NativeIntrinsicType::I64],
        result: NativeIntrinsicType::StrPtr,
        effect: NativeIntrinsicEffect::Pure,
    },
    NativeIntrinsic {
        module: "tcp",
        name: "connect",
        symbol: "lkrt_tcp_connect",
        params: &[NativeIntrinsicType::StrPtr],
        result: NativeIntrinsicType::I64,
        effect: NativeIntrinsicEffect::WritesHost,
    },
    NativeIntrinsic {
        module: "tcp",
        name: "read",
        symbol: "lkrt_tcp_read",
        params: &[NativeIntrinsicType::I64, NativeIntrinsicType::I64],
        result: NativeIntrinsicType::I64,
        effect: NativeIntrinsicEffect::WritesHost,
    },
    NativeIntrinsic {
        module: "tcp",
        name: "write_str",
        symbol: "lkrt_tcp_write_str",
        params: &[NativeIntrinsicType::I64, NativeIntrinsicType::StrPtr],
        result: NativeIntrinsicType::I64,
        effect: NativeIntrinsicEffect::WritesHost,
    },
    NativeIntrinsic {
        module: "tcp",
        name: "write_bytes",
        symbol: "lkrt_tcp_write_bytes",
        params: &[NativeIntrinsicType::I64, NativeIntrinsicType::I64],
        result: NativeIntrinsicType::I64,
        effect: NativeIntrinsicEffect::WritesHost,
    },
    NativeIntrinsic {
        module: "tcp",
        name: "close",
        symbol: "lkrt_tcp_close",
        params: &[NativeIntrinsicType::I64],
        result: NativeIntrinsicType::I64,
        effect: NativeIntrinsicEffect::WritesHost,
    },
    NativeIntrinsic {
        module: "bytes",
        name: "to_string_utf8",
        symbol: "lkrt_bytes_to_string_utf8",
        params: &[NativeIntrinsicType::I64],
        result: NativeIntrinsicType::StrPtr,
        effect: NativeIntrinsicEffect::Pure,
    },
    NativeIntrinsic {
        module: "bytes",
        name: "free",
        symbol: "lkrt_bytes_free",
        params: &[NativeIntrinsicType::I64],
        result: NativeIntrinsicType::I64,
        effect: NativeIntrinsicEffect::WritesHost,
    },
    NativeIntrinsic {
        module: "lkrt",
        name: "handle_close",
        symbol: "lkrt_handle_close",
        params: &[NativeIntrinsicType::I64],
        result: NativeIntrinsicType::I64,
        effect: NativeIntrinsicEffect::WritesHost,
    },
    NativeIntrinsic {
        module: "io.std",
        name: "write",
        symbol: "lkrt_io_std_write",
        params: &[
            NativeIntrinsicType::I64,
            NativeIntrinsicType::StrPtr,
            NativeIntrinsicType::I64,
        ],
        result: NativeIntrinsicType::I64,
        effect: NativeIntrinsicEffect::WritesHost,
    },
    NativeIntrinsic {
        module: "io.std",
        name: "flush",
        symbol: "lkrt_io_std_flush",
        params: &[NativeIntrinsicType::I64],
        result: NativeIntrinsicType::I64,
        effect: NativeIntrinsicEffect::WritesHost,
    },
    NativeIntrinsic {
        module: "io.std",
        name: "read_to_string",
        symbol: "lkrt_io_std_read_to_string",
        params: &[NativeIntrinsicType::I64],
        result: NativeIntrinsicType::StrPtr,
        effect: NativeIntrinsicEffect::WritesHost,
    },
    NativeIntrinsic {
        module: "env",
        name: "get",
        symbol: "lkrt_env_get",
        params: &[NativeIntrinsicType::StrPtr, NativeIntrinsicType::Ptr],
        result: NativeIntrinsicType::I64,
        effect: NativeIntrinsicEffect::ReadsHost,
    },
    NativeIntrinsic {
        module: "env",
        name: "get_or",
        symbol: "lkrt_env_get_or",
        params: &[NativeIntrinsicType::StrPtr, NativeIntrinsicType::StrPtr],
        result: NativeIntrinsicType::StrPtr,
        effect: NativeIntrinsicEffect::ReadsHost,
    },
    NativeIntrinsic {
        module: "env",
        name: "has",
        symbol: "lkrt_env_has",
        params: &[NativeIntrinsicType::StrPtr],
        result: NativeIntrinsicType::I64,
        effect: NativeIntrinsicEffect::ReadsHost,
    },
    NativeIntrinsic {
        module: "env",
        name: "set",
        symbol: "lkrt_env_set",
        params: &[NativeIntrinsicType::StrPtr, NativeIntrinsicType::StrPtr],
        result: NativeIntrinsicType::I64,
        effect: NativeIntrinsicEffect::WritesHost,
    },
    NativeIntrinsic {
        module: "env",
        name: "remove",
        symbol: "lkrt_env_remove",
        params: &[NativeIntrinsicType::StrPtr],
        result: NativeIntrinsicType::I64,
        effect: NativeIntrinsicEffect::WritesHost,
    },
    NativeIntrinsic {
        module: "fs",
        name: "read",
        symbol: "lkrt_fs_read",
        params: &[NativeIntrinsicType::StrPtr],
        result: NativeIntrinsicType::I64,
        effect: NativeIntrinsicEffect::ReadsHost,
    },
    NativeIntrinsic {
        module: "fs",
        name: "read_to_string",
        symbol: "lkrt_fs_read_to_string",
        params: &[NativeIntrinsicType::StrPtr],
        result: NativeIntrinsicType::StrPtr,
        effect: NativeIntrinsicEffect::ReadsHost,
    },
    NativeIntrinsic {
        module: "fs",
        name: "write_str",
        symbol: "lkrt_fs_write_str",
        params: &[NativeIntrinsicType::StrPtr, NativeIntrinsicType::StrPtr],
        result: NativeIntrinsicType::I64,
        effect: NativeIntrinsicEffect::WritesHost,
    },
    NativeIntrinsic {
        module: "fs",
        name: "write_bytes",
        symbol: "lkrt_fs_write_bytes",
        params: &[NativeIntrinsicType::StrPtr, NativeIntrinsicType::I64],
        result: NativeIntrinsicType::I64,
        effect: NativeIntrinsicEffect::WritesHost,
    },
    NativeIntrinsic {
        module: "fs",
        name: "exists",
        symbol: "lkrt_fs_exists",
        params: &[NativeIntrinsicType::StrPtr],
        result: NativeIntrinsicType::I64,
        effect: NativeIntrinsicEffect::ReadsHost,
    },
    NativeIntrinsic {
        module: "fs",
        name: "read_dir",
        symbol: "lkrt_fs_read_dir",
        params: &[NativeIntrinsicType::StrPtr],
        result: NativeIntrinsicType::I64,
        effect: NativeIntrinsicEffect::ReadsHost,
    },
    NativeIntrinsic {
        module: "fs",
        name: "metadata_len",
        symbol: "lkrt_fs_metadata_len",
        params: &[NativeIntrinsicType::StrPtr],
        result: NativeIntrinsicType::I64,
        effect: NativeIntrinsicEffect::ReadsHost,
    },
    NativeIntrinsic {
        module: "fs",
        name: "metadata_is_file",
        symbol: "lkrt_fs_metadata_is_file",
        params: &[NativeIntrinsicType::StrPtr],
        result: NativeIntrinsicType::I64,
        effect: NativeIntrinsicEffect::ReadsHost,
    },
    NativeIntrinsic {
        module: "fs",
        name: "metadata_is_dir",
        symbol: "lkrt_fs_metadata_is_dir",
        params: &[NativeIntrinsicType::StrPtr],
        result: NativeIntrinsicType::I64,
        effect: NativeIntrinsicEffect::ReadsHost,
    },
    NativeIntrinsic {
        module: "fs",
        name: "metadata_readonly",
        symbol: "lkrt_fs_metadata_readonly",
        params: &[NativeIntrinsicType::StrPtr],
        result: NativeIntrinsicType::I64,
        effect: NativeIntrinsicEffect::ReadsHost,
    },
    NativeIntrinsic {
        module: "fs",
        name: "canonicalize",
        symbol: "lkrt_fs_canonicalize",
        params: &[NativeIntrinsicType::StrPtr],
        result: NativeIntrinsicType::StrPtr,
        effect: NativeIntrinsicEffect::ReadsHost,
    },
    NativeIntrinsic {
        module: "fs",
        name: "temp_dir",
        symbol: "lkrt_fs_temp_dir",
        params: &[],
        result: NativeIntrinsicType::StrPtr,
        effect: NativeIntrinsicEffect::ReadsHost,
    },
    NativeIntrinsic {
        module: "path",
        name: "temp_dir",
        symbol: "lkrt_path_temp_dir",
        params: &[],
        result: NativeIntrinsicType::StrPtr,
        effect: NativeIntrinsicEffect::ReadsHost,
    },
    NativeIntrinsic {
        module: "process",
        name: "cwd",
        symbol: "lkrt_process_cwd",
        params: &[],
        result: NativeIntrinsicType::StrPtr,
        effect: NativeIntrinsicEffect::ReadsHost,
    },
    NativeIntrinsic {
        module: "os",
        name: "clock",
        symbol: "lkrt_os_clock",
        params: &[],
        result: NativeIntrinsicType::F64,
        effect: NativeIntrinsicEffect::ReadsHost,
    },
    NativeIntrinsic {
        module: "os",
        name: "epoch",
        symbol: "lkrt_os_epoch",
        params: &[],
        result: NativeIntrinsicType::I64,
        effect: NativeIntrinsicEffect::ReadsHost,
    },
    NativeIntrinsic {
        module: "time",
        name: "now",
        symbol: "lkrt_time_now_ms",
        params: &[],
        result: NativeIntrinsicType::I64,
        effect: NativeIntrinsicEffect::ReadsHost,
    },
    NativeIntrinsic {
        module: "time",
        name: "sleep",
        symbol: "lkrt_time_sleep_ms",
        params: &[NativeIntrinsicType::I64],
        result: NativeIntrinsicType::Nil,
        effect: NativeIntrinsicEffect::WritesHost,
    },
    // Monomorphized `DynamicList<i64>` container helpers. These are pure: they
    // only read the source buffer and write the caller-owned destination buffer.
    NativeIntrinsic {
        module: "list.i64",
        name: "contains",
        symbol: "lkrt_list_i64_contains",
        params: &[
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::I64,
        ],
        result: NativeIntrinsicType::I64,
        effect: NativeIntrinsicEffect::Pure,
    },
    NativeIntrinsic {
        module: "list.i64",
        name: "index_of",
        symbol: "lkrt_list_i64_index_of",
        params: &[
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::I64,
        ],
        result: NativeIntrinsicType::I64,
        effect: NativeIntrinsicEffect::Pure,
    },
    NativeIntrinsic {
        module: "list.i64",
        name: "reverse",
        symbol: "lkrt_list_i64_reverse",
        params: &[
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::Ptr,
        ],
        result: NativeIntrinsicType::Nil,
        effect: NativeIntrinsicEffect::Pure,
    },
    NativeIntrinsic {
        module: "list.i64",
        name: "sort",
        symbol: "lkrt_list_i64_sort",
        params: &[
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::Ptr,
        ],
        result: NativeIntrinsicType::Nil,
        effect: NativeIntrinsicEffect::Pure,
    },
    NativeIntrinsic {
        module: "list.i64",
        name: "pop",
        symbol: "lkrt_list_i64_pop",
        params: &[NativeIntrinsicType::Ptr, NativeIntrinsicType::I64],
        result: NativeIntrinsicType::I64,
        effect: NativeIntrinsicEffect::Pure,
    },
    NativeIntrinsic {
        module: "list.i64",
        name: "slice_range",
        symbol: "lkrt_list_i64_slice_range",
        params: &[
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::Ptr,
        ],
        result: NativeIntrinsicType::Nil,
        effect: NativeIntrinsicEffect::Pure,
    },
    NativeIntrinsic {
        module: "list.i64",
        name: "push",
        symbol: "lkrt_list_i64_push",
        params: &[
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::Ptr,
        ],
        result: NativeIntrinsicType::Nil,
        effect: NativeIntrinsicEffect::Pure,
    },
    NativeIntrinsic {
        module: "list.i64",
        name: "insert",
        symbol: "lkrt_list_i64_insert",
        params: &[
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::Ptr,
        ],
        result: NativeIntrinsicType::Nil,
        effect: NativeIntrinsicEffect::Pure,
    },
    NativeIntrinsic {
        module: "list.i64",
        name: "remove_at",
        symbol: "lkrt_list_i64_remove_at",
        params: &[
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::Ptr,
        ],
        result: NativeIntrinsicType::I64,
        effect: NativeIntrinsicEffect::Pure,
    },
    NativeIntrinsic {
        module: "list.i64",
        name: "set",
        symbol: "lkrt_list_i64_set",
        params: &[
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::Ptr,
        ],
        result: NativeIntrinsicType::I64,
        effect: NativeIntrinsicEffect::Pure,
    },
    NativeIntrinsic {
        module: "list.i64",
        name: "slice",
        symbol: "lkrt_list_i64_slice",
        params: &[
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::Ptr,
        ],
        result: NativeIntrinsicType::Nil,
        effect: NativeIntrinsicEffect::Pure,
    },
    NativeIntrinsic {
        module: "list.i64",
        name: "take",
        symbol: "lkrt_list_i64_take",
        params: &[
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::Ptr,
        ],
        result: NativeIntrinsicType::Nil,
        effect: NativeIntrinsicEffect::Pure,
    },
    NativeIntrinsic {
        module: "list.i64",
        name: "concat",
        symbol: "lkrt_list_i64_concat",
        params: &[
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::Ptr,
        ],
        result: NativeIntrinsicType::Nil,
        effect: NativeIntrinsicEffect::Pure,
    },
    NativeIntrinsic {
        module: "list.i64",
        name: "eq",
        symbol: "lkrt_list_i64_eq",
        params: &[
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::I64,
        ],
        result: NativeIntrinsicType::I64,
        effect: NativeIntrinsicEffect::Pure,
    },
    // Monomorphized `DynamicList<f64>` container helpers. Same pure contract as
    // the i64 helpers; comparisons follow `fcmp` (NaN-aware) semantics.
    NativeIntrinsic {
        module: "list.f64",
        name: "contains",
        symbol: "lkrt_list_f64_contains",
        params: &[
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::F64,
        ],
        result: NativeIntrinsicType::I64,
        effect: NativeIntrinsicEffect::Pure,
    },
    NativeIntrinsic {
        module: "list.f64",
        name: "index_of",
        symbol: "lkrt_list_f64_index_of",
        params: &[
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::F64,
        ],
        result: NativeIntrinsicType::I64,
        effect: NativeIntrinsicEffect::Pure,
    },
    NativeIntrinsic {
        module: "list.f64",
        name: "reverse",
        symbol: "lkrt_list_f64_reverse",
        params: &[
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::Ptr,
        ],
        result: NativeIntrinsicType::Nil,
        effect: NativeIntrinsicEffect::Pure,
    },
    NativeIntrinsic {
        module: "list.f64",
        name: "sort",
        symbol: "lkrt_list_f64_sort",
        params: &[
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::Ptr,
        ],
        result: NativeIntrinsicType::Nil,
        effect: NativeIntrinsicEffect::Pure,
    },
    NativeIntrinsic {
        module: "list.f64",
        name: "pop",
        symbol: "lkrt_list_f64_pop",
        params: &[NativeIntrinsicType::Ptr, NativeIntrinsicType::I64],
        result: NativeIntrinsicType::F64,
        effect: NativeIntrinsicEffect::Pure,
    },
    NativeIntrinsic {
        module: "list.f64",
        name: "slice",
        symbol: "lkrt_list_f64_slice",
        params: &[
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::Ptr,
        ],
        result: NativeIntrinsicType::Nil,
        effect: NativeIntrinsicEffect::Pure,
    },
    NativeIntrinsic {
        module: "list.f64",
        name: "slice_range",
        symbol: "lkrt_list_f64_slice_range",
        params: &[
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::Ptr,
        ],
        result: NativeIntrinsicType::Nil,
        effect: NativeIntrinsicEffect::Pure,
    },
    NativeIntrinsic {
        module: "list.f64",
        name: "take",
        symbol: "lkrt_list_f64_take",
        params: &[
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::Ptr,
        ],
        result: NativeIntrinsicType::Nil,
        effect: NativeIntrinsicEffect::Pure,
    },
    NativeIntrinsic {
        module: "list.f64",
        name: "concat",
        symbol: "lkrt_list_f64_concat",
        params: &[
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::Ptr,
        ],
        result: NativeIntrinsicType::Nil,
        effect: NativeIntrinsicEffect::Pure,
    },
    NativeIntrinsic {
        module: "list.f64",
        name: "unique",
        symbol: "lkrt_list_f64_unique",
        params: &[
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::Ptr,
        ],
        result: NativeIntrinsicType::Nil,
        effect: NativeIntrinsicEffect::Pure,
    },
    NativeIntrinsic {
        module: "list.f64",
        name: "push",
        symbol: "lkrt_list_f64_push",
        params: &[
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::F64,
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::Ptr,
        ],
        result: NativeIntrinsicType::Nil,
        effect: NativeIntrinsicEffect::Pure,
    },
    NativeIntrinsic {
        module: "list.f64",
        name: "insert",
        symbol: "lkrt_list_f64_insert",
        params: &[
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::F64,
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::Ptr,
        ],
        result: NativeIntrinsicType::Nil,
        effect: NativeIntrinsicEffect::Pure,
    },
    NativeIntrinsic {
        module: "list.f64",
        name: "remove_at",
        symbol: "lkrt_list_f64_remove_at",
        params: &[
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::Ptr,
        ],
        result: NativeIntrinsicType::F64,
        effect: NativeIntrinsicEffect::Pure,
    },
    NativeIntrinsic {
        module: "list.f64",
        name: "set",
        symbol: "lkrt_list_f64_set",
        params: &[
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::F64,
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::Ptr,
        ],
        result: NativeIntrinsicType::F64,
        effect: NativeIntrinsicEffect::Pure,
    },
    // Monomorphized `DynamicList<str>` (C string pointer) container helpers.
    // Structural ops move pointers; push/insert/set duplicate the injected value.
    NativeIntrinsic {
        module: "list.str",
        name: "contains",
        symbol: "lkrt_list_str_contains",
        params: &[
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::StrPtr,
        ],
        result: NativeIntrinsicType::I64,
        effect: NativeIntrinsicEffect::Pure,
    },
    NativeIntrinsic {
        module: "list.str",
        name: "index_of",
        symbol: "lkrt_list_str_index_of",
        params: &[
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::StrPtr,
        ],
        result: NativeIntrinsicType::I64,
        effect: NativeIntrinsicEffect::Pure,
    },
    NativeIntrinsic {
        module: "list.str",
        name: "text_len",
        symbol: "lkrt_list_str_text_len",
        params: &[NativeIntrinsicType::Ptr, NativeIntrinsicType::I64],
        result: NativeIntrinsicType::I64,
        effect: NativeIntrinsicEffect::Pure,
    },
    NativeIntrinsic {
        module: "list.str",
        name: "reverse",
        symbol: "lkrt_list_str_reverse",
        params: &[
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::Ptr,
        ],
        result: NativeIntrinsicType::Nil,
        effect: NativeIntrinsicEffect::Pure,
    },
    NativeIntrinsic {
        module: "list.str",
        name: "sort",
        symbol: "lkrt_list_str_sort",
        params: &[
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::Ptr,
        ],
        result: NativeIntrinsicType::Nil,
        effect: NativeIntrinsicEffect::Pure,
    },
    NativeIntrinsic {
        module: "list.str",
        name: "pop",
        symbol: "lkrt_list_str_pop",
        params: &[NativeIntrinsicType::Ptr, NativeIntrinsicType::I64],
        result: NativeIntrinsicType::StrPtr,
        effect: NativeIntrinsicEffect::Pure,
    },
    NativeIntrinsic {
        module: "list.str",
        name: "slice_range",
        symbol: "lkrt_list_str_slice_range",
        params: &[
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::Ptr,
        ],
        result: NativeIntrinsicType::Nil,
        effect: NativeIntrinsicEffect::Pure,
    },
    NativeIntrinsic {
        module: "list.str",
        name: "push",
        symbol: "lkrt_list_str_push",
        params: &[
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::StrPtr,
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::Ptr,
        ],
        result: NativeIntrinsicType::Nil,
        effect: NativeIntrinsicEffect::Pure,
    },
    NativeIntrinsic {
        module: "list.str",
        name: "insert",
        symbol: "lkrt_list_str_insert",
        params: &[
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::StrPtr,
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::Ptr,
        ],
        result: NativeIntrinsicType::Nil,
        effect: NativeIntrinsicEffect::Pure,
    },
    NativeIntrinsic {
        module: "list.str",
        name: "remove_at",
        symbol: "lkrt_list_str_remove_at",
        params: &[
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::Ptr,
        ],
        result: NativeIntrinsicType::StrPtr,
        effect: NativeIntrinsicEffect::Pure,
    },
    NativeIntrinsic {
        module: "list.str",
        name: "set",
        symbol: "lkrt_list_str_set",
        params: &[
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::StrPtr,
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::Ptr,
        ],
        result: NativeIntrinsicType::StrPtr,
        effect: NativeIntrinsicEffect::Pure,
    },
    NativeIntrinsic {
        module: "list.str",
        name: "slice",
        symbol: "lkrt_list_str_slice",
        params: &[
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::Ptr,
        ],
        result: NativeIntrinsicType::Nil,
        effect: NativeIntrinsicEffect::Pure,
    },
    NativeIntrinsic {
        module: "list.str",
        name: "take",
        symbol: "lkrt_list_str_take",
        params: &[
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::Ptr,
        ],
        result: NativeIntrinsicType::Nil,
        effect: NativeIntrinsicEffect::Pure,
    },
    NativeIntrinsic {
        module: "list.str",
        name: "concat",
        symbol: "lkrt_list_str_concat",
        params: &[
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::Ptr,
        ],
        result: NativeIntrinsicType::Nil,
        effect: NativeIntrinsicEffect::Pure,
    },
    // Monomorphized `DynamicMap<i64, V>` lookup/set helpers (parallel key/value
    // arrays). `lookup` writes the found value through `out` and returns 1/0;
    // `set` updates in place or appends, returning the new length.
    NativeIntrinsic {
        module: "map.i64",
        name: "int_lookup",
        symbol: "lkrt_map_i64_int_lookup",
        params: &[
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::Ptr,
        ],
        result: NativeIntrinsicType::I64,
        effect: NativeIntrinsicEffect::Pure,
    },
    NativeIntrinsic {
        module: "map.i64",
        name: "f64_lookup",
        symbol: "lkrt_map_i64_f64_lookup",
        params: &[
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::Ptr,
        ],
        result: NativeIntrinsicType::I64,
        effect: NativeIntrinsicEffect::Pure,
    },
    NativeIntrinsic {
        module: "map.i64",
        name: "ptr_lookup",
        symbol: "lkrt_map_i64_ptr_lookup",
        params: &[
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::Ptr,
        ],
        result: NativeIntrinsicType::I64,
        effect: NativeIntrinsicEffect::Pure,
    },
    NativeIntrinsic {
        module: "map.i64",
        name: "int_set",
        symbol: "lkrt_map_i64_int_set",
        params: &[
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::I64,
        ],
        result: NativeIntrinsicType::I64,
        effect: NativeIntrinsicEffect::Pure,
    },
    NativeIntrinsic {
        module: "map.i64",
        name: "f64_set",
        symbol: "lkrt_map_i64_f64_set",
        params: &[
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::F64,
        ],
        result: NativeIntrinsicType::I64,
        effect: NativeIntrinsicEffect::Pure,
    },
    NativeIntrinsic {
        module: "map.i64",
        name: "ptr_set",
        symbol: "lkrt_map_i64_ptr_set",
        params: &[
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::StrPtr,
        ],
        result: NativeIntrinsicType::I64,
        effect: NativeIntrinsicEffect::Pure,
    },
    // Monomorphized `DynamicMap<str, V>` helpers with a composite short-string key
    // (string prefix + integer suffix). `split_key` parses a key into that pair;
    // lookup/set compare with `strcmp(prefix) && number ==`.
    NativeIntrinsic {
        module: "map.str",
        name: "split_key",
        symbol: "lkrt_map_str_split_key",
        params: &[NativeIntrinsicType::StrPtr, NativeIntrinsicType::Ptr],
        result: NativeIntrinsicType::I64,
        effect: NativeIntrinsicEffect::Pure,
    },
    NativeIntrinsic {
        module: "map.str",
        name: "int_lookup",
        symbol: "lkrt_map_str_int_lookup",
        params: &[
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::StrPtr,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::Ptr,
        ],
        result: NativeIntrinsicType::I64,
        effect: NativeIntrinsicEffect::Pure,
    },
    NativeIntrinsic {
        module: "map.str",
        name: "int_set",
        symbol: "lkrt_map_str_int_set",
        params: &[
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::StrPtr,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::I64,
        ],
        result: NativeIntrinsicType::I64,
        effect: NativeIntrinsicEffect::Pure,
    },
    NativeIntrinsic {
        module: "map.str",
        name: "f64_lookup",
        symbol: "lkrt_map_str_f64_lookup",
        params: &[
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::StrPtr,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::Ptr,
        ],
        result: NativeIntrinsicType::I64,
        effect: NativeIntrinsicEffect::Pure,
    },
    NativeIntrinsic {
        module: "map.str",
        name: "f64_set",
        symbol: "lkrt_map_str_f64_set",
        params: &[
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::StrPtr,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::F64,
        ],
        result: NativeIntrinsicType::I64,
        effect: NativeIntrinsicEffect::Pure,
    },
    NativeIntrinsic {
        module: "map.str",
        name: "ptr_lookup",
        symbol: "lkrt_map_str_ptr_lookup",
        params: &[
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::StrPtr,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::Ptr,
        ],
        result: NativeIntrinsicType::I64,
        effect: NativeIntrinsicEffect::Pure,
    },
    NativeIntrinsic {
        module: "map.str",
        name: "ptr_set",
        symbol: "lkrt_map_str_ptr_set",
        params: &[
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::StrPtr,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::StrPtr,
        ],
        result: NativeIntrinsicType::I64,
        effect: NativeIntrinsicEffect::Pure,
    },
    NativeIntrinsic {
        module: "map.str",
        name: "contains",
        symbol: "lkrt_map_str_contains",
        params: &[
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::StrPtr,
            NativeIntrinsicType::I64,
        ],
        result: NativeIntrinsicType::I64,
        effect: NativeIntrinsicEffect::Pure,
    },
    // `DynamicMap<str, V>` compaction delete: copies non-matching entries into a
    // destination map, writing the removed value through `out_value` / presence
    // through `out_present`, and returns the destination length.
    NativeIntrinsic {
        module: "map.str",
        name: "int_delete",
        symbol: "lkrt_map_str_int_delete",
        params: &[
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::StrPtr,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::Ptr,
        ],
        result: NativeIntrinsicType::I64,
        effect: NativeIntrinsicEffect::Pure,
    },
    NativeIntrinsic {
        module: "map.str",
        name: "f64_delete",
        symbol: "lkrt_map_str_f64_delete",
        params: &[
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::StrPtr,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::Ptr,
        ],
        result: NativeIntrinsicType::I64,
        effect: NativeIntrinsicEffect::Pure,
    },
    NativeIntrinsic {
        module: "map.str",
        name: "ptr_delete",
        symbol: "lkrt_map_str_ptr_delete",
        params: &[
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::StrPtr,
            NativeIntrinsicType::I64,
            NativeIntrinsicType::Ptr,
            NativeIntrinsicType::Ptr,
        ],
        result: NativeIntrinsicType::I64,
        effect: NativeIntrinsicEffect::Pure,
    },
    NativeIntrinsic {
        module: "fmt",
        name: "i64_decimal_len",
        symbol: "lkrt_i64_decimal_len",
        params: &[NativeIntrinsicType::I64],
        result: NativeIntrinsicType::I64,
        effect: NativeIntrinsicEffect::Pure,
    },
];

pub(in crate::llvm) fn native_intrinsic(module: &str, name: &str) -> Option<&'static NativeIntrinsic> {
    NATIVE_INTRINSICS
        .iter()
        .find(|intrinsic| intrinsic.module == module && intrinsic.name == name)
}

pub(in crate::llvm) fn native_intrinsic_declarations() -> String {
    let mut declarations = String::new();
    for intrinsic in NATIVE_INTRINSICS {
        if !intrinsic.symbol.starts_with("lkrt_") {
            continue;
        }
        declarations.push_str("declare ");
        declarations.push_str(llvm_type(intrinsic.result));
        declarations.push_str(" @");
        declarations.push_str(intrinsic.symbol);
        declarations.push('(');
        for (index, param) in intrinsic.params.iter().enumerate() {
            if index > 0 {
                declarations.push_str(", ");
            }
            declarations.push_str(llvm_type(*param));
        }
        declarations.push_str(")\n");
    }
    declarations.push('\n');
    declarations
}

fn llvm_type(value: NativeIntrinsicType) -> &'static str {
    match value {
        NativeIntrinsicType::I64 => "i64",
        NativeIntrinsicType::F64 => "double",
        NativeIntrinsicType::Ptr | NativeIntrinsicType::StrPtr => "ptr",
        NativeIntrinsicType::Nil => "void",
    }
}
