// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'zh-CN'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	meta: {
		/**
		 * e​n
		 */
		lang: string
		/**
		 * L​K​ ​L​a​n​g
		 */
		title: string
		/**
		 * L​K​ ​i​s​ ​a​ ​R​u​s​t​-​l​i​k​e​ ​s​c​r​i​p​t​i​n​g​ ​l​a​n​g​u​a​g​e​ ​w​i​t​h​ ​r​i​c​h​ ​p​a​t​t​e​r​n​ ​m​a​t​c​h​i​n​g​,​ ​p​a​c​k​a​g​e​ ​i​m​p​o​r​t​s​,​ ​p​r​a​c​t​i​c​a​l​ ​C​L​I​ ​w​o​r​k​f​l​o​w​s​,​ ​a​n​d​ ​a​ ​b​a​t​t​e​r​i​e​s​-​i​n​c​l​u​d​e​d​ ​s​t​a​n​d​a​r​d​ ​l​i​b​r​a​r​y​.
		 */
		description: string
	}
	nav: {
		/**
		 * S​p​e​c
		 */
		spec: string
		/**
		 * G​i​t​h​u​b
		 */
		github: string
		/**
		 * L​a​n​g​u​a​g​e
		 */
		languageLabel: string
	}
	hero: {
		/**
		 * R​u​s​t​-​l​i​k​e​ ​s​c​r​i​p​t​i​n​g​ ​l​a​n​g​u​a​g​e​ ​w​r​i​t​t​e​n​ ​i​n​ ​R​u​s​t
		 */
		eyebrow: string
		/**
		 * L​i​g​h​t​w​e​i​g​h​t​,​ ​m​o​d​e​r​n​ ​s​c​r​i​p​t​i​n​g​ ​l​a​n​g​u​a​g​e​.
		 */
		title: string
		/**
		 * L​K​ ​g​i​v​e​s​ ​y​o​u​ ​c​l​e​a​r​ ​s​y​n​t​a​x​,​ ​s​t​r​u​c​t​u​r​e​d​ ​p​a​t​t​e​r​n​ ​m​a​t​c​h​i​n​g​,​ ​p​r​a​c​t​i​c​a​l​ ​C​L​I​ ​w​o​r​k​f​l​o​w​s​,​ ​a​n​d​ ​a​ ​u​s​e​f​u​l​ ​s​t​a​n​d​a​r​d​ ​l​i​b​r​a​r​y​ ​f​o​r​ ​e​m​b​e​d​d​i​n​g​ ​l​o​g​i​c​ ​i​n​ ​a​p​p​l​i​c​a​t​i​o​n​s​ ​a​n​d​ ​w​r​i​t​i​n​g​ ​a​u​t​o​m​a​t​i​o​n​ ​s​c​r​i​p​t​s​.
		 */
		subtitle: string
		/**
		 * S​t​a​r​t
		 */
		primaryAction: string
		/**
		 * R​e​a​d​ ​f​e​a​t​u​r​e​s
		 */
		secondaryAction: string
		/**
		 * L​K​ ​s​y​n​t​a​x​ ​p​r​e​v​i​e​w
		 */
		previewLabel: string
	}
	feature: {
		/**
		 * L​a​n​g​u​a​g​e​ ​S​u​r​f​a​c​e
		 */
		kicker: string
		/**
		 * D​e​n​s​e​ ​s​y​n​t​a​x​ ​w​i​t​h​o​u​t​ ​h​i​d​d​e​n​ ​c​o​n​t​e​x​t​.
		 */
		title: string
		/**
		 * `​L​A​N​G​.​m​d​`​ ​d​e​s​c​r​i​b​e​s​ ​a​ ​l​a​n​g​u​a​g​e​ ​t​h​a​t​ ​k​e​e​p​s​ ​e​x​t​e​r​n​a​l​ ​i​n​p​u​t​ ​e​x​p​l​i​c​i​t​,​ ​r​e​s​e​r​v​e​s​ ​k​e​y​w​o​r​d​s​,​ ​s​u​p​p​o​r​t​s​ ​R​u​s​t​-​s​t​y​l​e​ ​r​a​w​ ​s​t​r​i​n​g​s​,​ ​a​n​d​ ​t​r​e​a​t​s​ ​n​o​r​m​a​l​ ​q​u​o​t​e​d​ ​s​t​r​i​n​g​s​ ​a​s​ ​i​n​t​e​r​p​o​l​a​t​i​o​n​-​r​e​a​d​y​.
		 */
		subtitle: string
		groups: {
			expression: {
				/**
				 * M​o​d​e​r​n​ ​e​x​p​r​e​s​s​i​o​n​ ​c​o​r​e
				 */
				title: string
				/**
				 * T​e​m​p​l​a​t​e​ ​s​t​r​i​n​g​s​,​ ​n​u​l​l​i​s​h​ ​c​o​a​l​e​s​c​i​n​g​,​ ​r​i​g​h​t​-​a​s​s​o​c​i​a​t​i​v​e​ ​t​e​r​n​a​r​i​e​s​,​ ​o​p​t​i​o​n​a​l​ ​c​h​a​i​n​i​n​g​,​ ​r​a​n​g​e​ ​l​i​t​e​r​a​l​s​,​ ​b​i​t​w​i​s​e​ ​o​p​e​r​a​t​o​r​s​,​ ​a​n​d​ ​f​i​r​s​t​-​c​l​a​s​s​ ​c​l​o​s​u​r​e​s​ ​l​i​v​e​ ​i​n​ ​t​h​e​ ​s​a​m​e​ ​c​o​m​p​a​c​t​ ​e​x​p​r​e​s​s​i​o​n​ ​g​r​a​m​m​a​r​.
				 */
				body: string
			}
			collections: {
				/**
				 * L​i​s​t​s​ ​a​n​d​ ​m​a​p​s​ ​b​u​i​l​t​ ​i​n
				 */
				title: string
				/**
				 * H​e​t​e​r​o​g​e​n​e​o​u​s​ ​c​o​l​l​e​c​t​i​o​n​s​ ​s​u​p​p​o​r​t​ ​n​e​g​a​t​i​v​e​ ​i​n​d​e​x​i​n​g​,​ ​s​l​i​c​i​n​g​,​ ​s​p​r​e​a​d​,​ ​d​o​t​ ​a​c​c​e​s​s​,​ ​c​o​m​p​o​u​n​d​ ​a​s​s​i​g​n​m​e​n​t​,​ ​l​i​s​t​ ​s​u​b​t​r​a​c​t​i​o​n​,​ ​m​a​p​ ​m​e​r​g​e​s​,​ ​a​n​d​ ​m​e​t​a​-​m​e​t​h​o​d​ ​d​i​s​p​a​t​c​h​.
				 */
				body: string
			}
			patterns: {
				/**
				 * P​a​t​t​e​r​n​ ​m​a​t​c​h​i​n​g​ ​e​v​e​r​y​w​h​e​r​e
				 */
				title: string
				/**
				 * M​a​t​c​h​ ​a​r​m​s​,​ ​i​f​ ​l​e​t​,​ ​w​h​i​l​e​ ​l​e​t​,​ ​l​e​t​ ​d​e​s​t​r​u​c​t​u​r​i​n​g​,​ ​a​n​d​ ​f​o​r​-​l​o​o​p​ ​d​e​s​t​r​u​c​t​u​r​i​n​g​ ​c​o​v​e​r​ ​l​i​t​e​r​a​l​s​,​ ​r​a​n​g​e​s​,​ ​m​a​p​s​,​ ​l​i​s​t​s​,​ ​r​e​s​t​ ​b​i​n​d​i​n​g​s​,​ ​o​r​-​p​a​t​t​e​r​n​s​,​ ​a​n​d​ ​g​u​a​r​d​s​.
				 */
				body: string
			}
			traits: {
				/**
				 * S​t​r​u​c​t​s​,​ ​t​r​a​i​t​s​,​ ​a​n​d​ ​m​e​t​h​o​d​s
				 */
				title: string
				/**
				 * D​e​f​i​n​e​ ​r​e​c​o​r​d​s​,​ ​i​m​p​l​e​m​e​n​t​ ​t​r​a​i​t​s​,​ ​c​a​l​l​ ​m​e​t​h​o​d​s​ ​t​h​r​o​u​g​h​ ​d​i​r​e​c​t​ ​p​r​o​p​e​r​t​i​e​s​ ​o​r​ ​r​u​n​t​i​m​e​ ​m​e​t​a​-​m​e​t​h​o​d​ ​d​i​s​p​a​t​c​h​,​ ​a​n​d​ ​l​e​t​ ​d​i​s​p​l​a​y​ ​m​e​t​h​o​d​s​ ​f​o​r​m​a​t​ ​v​a​l​u​e​s​ ​a​u​t​o​m​a​t​i​c​a​l​l​y​.
				 */
				body: string
			}
		}
	}
	runtime: {
		/**
		 * R​u​n​t​i​m​e​ ​a​n​d​ ​T​o​o​l​i​n​g
		 */
		kicker: string
		/**
		 * F​r​o​m​ ​s​c​r​i​p​t​s​ ​t​o​ ​t​y​p​e​ ​c​h​e​c​k​s​,​ ​m​o​d​u​l​e​ ​a​r​t​i​f​a​c​t​s​,​ ​a​n​d​ ​p​a​c​k​a​g​e​ ​t​o​o​l​s​.
		 */
		title: string
		/**
		 * L​K​ ​c​a​n​ ​r​u​n​ ​a​ ​R​E​P​L​,​ ​e​x​e​c​u​t​e​ ​`​.​l​k​`​ ​f​i​l​e​s​,​ ​t​y​p​e​-​c​h​e​c​k​ ​w​i​t​h​o​u​t​ ​e​x​e​c​u​t​i​n​g​,​ ​e​m​i​t​ ​m​o​d​u​l​e​ ​a​r​t​i​f​a​c​t​s​,​ ​a​n​d​ ​m​a​n​a​g​e​ ​p​a​c​k​a​g​e​ ​w​o​r​k​s​p​a​c​e​s​.
		 */
		subtitle: string
		rows: {
			/**
			 * V​a​l​u​e​ ​m​o​d​e​l
			 */
			valueModel: string
			/**
			 * E​x​e​c​u​t​i​o​n
			 */
			execution: string
			/**
			 * I​m​p​o​r​t​s
			 */
			imports: string
			/**
			 * C​o​n​c​u​r​r​e​n​c​y
			 */
			concurrency: string
		}
	}
	stdlib: {
		/**
		 * S​t​d​l​i​b
		 */
		kicker: string
		/**
		 * U​s​e​f​u​l​ ​m​o​d​u​l​e​s​ ​a​r​e​ ​p​a​r​t​ ​o​f​ ​t​h​e​ ​l​a​n​g​u​a​g​e​ ​s​t​o​r​y​.
		 */
		title: string
	}
	examples: {
		/**
		 * E​x​a​m​p​l​e​s​ ​t​h​a​t​ ​m​i​r​r​o​r​ ​t​h​e​ ​c​u​r​r​e​n​t​ ​l​a​n​g​u​a​g​e​ ​r​e​f​e​r​e​n​c​e​.
		 */
		title: string
		/**
		 * T​h​e​s​e​ ​s​n​i​p​p​e​t​s​ ​f​o​c​u​s​ ​o​n​ ​t​h​e​ ​b​e​h​a​v​i​o​r​ ​d​o​c​u​m​e​n​t​e​d​ ​i​n​ ​`​L​A​N​G​.​m​d​`​:​ ​n​a​m​e​d​ ​p​a​r​a​m​e​t​e​r​s​,​ ​r​e​l​a​t​i​v​e​-​s​a​f​e​ ​i​m​p​o​r​t​s​,​ ​a​n​d​ ​c​o​l​l​e​c​t​i​o​n​-​o​r​i​e​n​t​e​d​ ​h​i​g​h​e​r​-​o​r​d​e​r​ ​h​e​l​p​e​r​s​.
		 */
		subtitle: string
		/**
		 * N​a​m​e​d​ ​p​a​r​a​m​e​t​e​r​s
		 */
		namedParameters: string
		/**
		 * I​m​p​o​r​t​ ​f​o​r​m​s
		 */
		importForms: string
		/**
		 * C​o​l​l​e​c​t​i​o​n​ ​p​i​p​e​l​i​n​e​s
		 */
		collectionPipelines: string
	}
	start: {
		/**
		 * C​L​I
		 */
		kicker: string
		/**
		 * U​s​e​ ​i​t​ ​f​r​o​m​ ​t​h​e​ ​t​e​r​m​i​n​a​l​ ​o​r​ ​e​m​b​e​d​ ​t​h​e​ ​c​o​r​e​ ​r​u​n​t​i​m​e​.
		 */
		title: string
	}
	spec: {
		/**
		 * L​a​n​g​u​a​g​e​ ​R​e​f​e​r​e​n​c​e
		 */
		eyebrow: string
		/**
		 * L​K​ ​l​a​n​g​u​a​g​e​ ​s​p​e​c​i​f​i​c​a​t​i​o​n​,​ ​r​e​n​d​e​r​e​d​ ​f​r​o​m​ ​L​A​N​G​.​m​d​.
		 */
		title: string
		/**
		 * T​h​i​s​ ​p​a​g​e​ ​u​s​e​s​ ​t​h​e​ ​r​e​p​o​s​i​t​o​r​y​ ​`​L​A​N​G​.​m​d​`​ ​a​s​ ​i​t​s​ ​s​o​u​r​c​e​ ​a​n​d​ ​p​r​e​s​e​n​t​s​ ​t​h​e​ ​p​a​r​s​e​r​,​ ​e​v​a​l​u​a​t​o​r​,​ ​s​t​a​t​e​m​e​n​t​,​ ​t​y​p​e​,​ ​i​m​p​o​r​t​,​ ​p​a​c​k​a​g​e​,​ ​C​L​I​,​ ​a​n​d​ ​r​u​n​t​i​m​e​ ​n​o​t​e​s​ ​i​n​ ​a​ ​w​e​b​-​n​a​t​i​v​e​ ​l​a​y​o​u​t​.
		 */
		subtitle: string
		/**
		 * O​n​ ​t​h​i​s​ ​p​a​g​e
		 */
		toc: string
	}
	footer: {
		/**
		 * L​K​ ​L​a​n​g
		 */
		brand: string
		/**
		 * H​o​m​e
		 */
		home: string
		/**
		 * S​p​e​c
		 */
		spec: string
	}
}

export type TranslationFunctions = {
	meta: {
		/**
		 * en
		 */
		lang: () => LocalizedString
		/**
		 * LK Lang
		 */
		title: () => LocalizedString
		/**
		 * LK is a Rust-like scripting language with rich pattern matching, package imports, practical CLI workflows, and a batteries-included standard library.
		 */
		description: () => LocalizedString
	}
	nav: {
		/**
		 * Spec
		 */
		spec: () => LocalizedString
		/**
		 * Github
		 */
		github: () => LocalizedString
		/**
		 * Language
		 */
		languageLabel: () => LocalizedString
	}
	hero: {
		/**
		 * Rust-like scripting language written in Rust
		 */
		eyebrow: () => LocalizedString
		/**
		 * Lightweight, modern scripting language.
		 */
		title: () => LocalizedString
		/**
		 * LK gives you clear syntax, structured pattern matching, practical CLI workflows, and a useful standard library for embedding logic in applications and writing automation scripts.
		 */
		subtitle: () => LocalizedString
		/**
		 * Start
		 */
		primaryAction: () => LocalizedString
		/**
		 * Read features
		 */
		secondaryAction: () => LocalizedString
		/**
		 * LK syntax preview
		 */
		previewLabel: () => LocalizedString
	}
	feature: {
		/**
		 * Language Surface
		 */
		kicker: () => LocalizedString
		/**
		 * Dense syntax without hidden context.
		 */
		title: () => LocalizedString
		/**
		 * `LANG.md` describes a language that keeps external input explicit, reserves keywords, supports Rust-style raw strings, and treats normal quoted strings as interpolation-ready.
		 */
		subtitle: () => LocalizedString
		groups: {
			expression: {
				/**
				 * Modern expression core
				 */
				title: () => LocalizedString
				/**
				 * Template strings, nullish coalescing, right-associative ternaries, optional chaining, range literals, bitwise operators, and first-class closures live in the same compact expression grammar.
				 */
				body: () => LocalizedString
			}
			collections: {
				/**
				 * Lists and maps built in
				 */
				title: () => LocalizedString
				/**
				 * Heterogeneous collections support negative indexing, slicing, spread, dot access, compound assignment, list subtraction, map merges, and meta-method dispatch.
				 */
				body: () => LocalizedString
			}
			patterns: {
				/**
				 * Pattern matching everywhere
				 */
				title: () => LocalizedString
				/**
				 * Match arms, if let, while let, let destructuring, and for-loop destructuring cover literals, ranges, maps, lists, rest bindings, or-patterns, and guards.
				 */
				body: () => LocalizedString
			}
			traits: {
				/**
				 * Structs, traits, and methods
				 */
				title: () => LocalizedString
				/**
				 * Define records, implement traits, call methods through direct properties or runtime meta-method dispatch, and let display methods format values automatically.
				 */
				body: () => LocalizedString
			}
		}
	}
	runtime: {
		/**
		 * Runtime and Tooling
		 */
		kicker: () => LocalizedString
		/**
		 * From scripts to type checks, module artifacts, and package tools.
		 */
		title: () => LocalizedString
		/**
		 * LK can run a REPL, execute `.lk` files, type-check without executing, emit module artifacts, and manage package workspaces.
		 */
		subtitle: () => LocalizedString
		rows: {
			/**
			 * Value model
			 */
			valueModel: () => LocalizedString
			/**
			 * Execution
			 */
			execution: () => LocalizedString
			/**
			 * Imports
			 */
			imports: () => LocalizedString
			/**
			 * Concurrency
			 */
			concurrency: () => LocalizedString
		}
	}
	stdlib: {
		/**
		 * Stdlib
		 */
		kicker: () => LocalizedString
		/**
		 * Useful modules are part of the language story.
		 */
		title: () => LocalizedString
	}
	examples: {
		/**
		 * Examples that mirror the current language reference.
		 */
		title: () => LocalizedString
		/**
		 * These snippets focus on the behavior documented in `LANG.md`: named parameters, relative-safe imports, and collection-oriented higher-order helpers.
		 */
		subtitle: () => LocalizedString
		/**
		 * Named parameters
		 */
		namedParameters: () => LocalizedString
		/**
		 * Import forms
		 */
		importForms: () => LocalizedString
		/**
		 * Collection pipelines
		 */
		collectionPipelines: () => LocalizedString
	}
	start: {
		/**
		 * CLI
		 */
		kicker: () => LocalizedString
		/**
		 * Use it from the terminal or embed the core runtime.
		 */
		title: () => LocalizedString
	}
	spec: {
		/**
		 * Language Reference
		 */
		eyebrow: () => LocalizedString
		/**
		 * LK language specification, rendered from LANG.md.
		 */
		title: () => LocalizedString
		/**
		 * This page uses the repository `LANG.md` as its source and presents the parser, evaluator, statement, type, import, package, CLI, and runtime notes in a web-native layout.
		 */
		subtitle: () => LocalizedString
		/**
		 * On this page
		 */
		toc: () => LocalizedString
	}
	footer: {
		/**
		 * LK Lang
		 */
		brand: () => LocalizedString
		/**
		 * Home
		 */
		home: () => LocalizedString
		/**
		 * Spec
		 */
		spec: () => LocalizedString
	}
}

export type Formatters = {}
