use super::*;

pub(crate) fn ast_macro_origin_symbol(origin: &macro_system::AstMacroOrigin) -> Option<DocumentSymbol> {
    let range = origin.input_span.as_ref().map(span_range)?;
    let children = if origin.generated_item_origins.is_empty() {
        origin
            .generated_item_labels
            .iter()
            .map(|label| fallback_generated_item_origin_symbol(label, origin, range))
            .collect::<Vec<_>>()
    } else {
        origin
            .generated_item_origins
            .iter()
            .map(|item| generated_item_origin_symbol(item, origin, range))
            .collect::<Vec<_>>()
    };
    Some(DocumentSymbol {
        name: format!("{} {}", origin.kind.as_str(), origin.macro_name),
        detail: Some(format!("generated {} item(s)", origin.generated_items)),
        kind: SymbolKind::NAMESPACE,
        tags: None,
        #[allow(deprecated)]
        deprecated: None,
        range,
        selection_range: range,
        children: (!children.is_empty()).then_some(children),
    })
}

pub(crate) fn symbols_range(symbols: &[DocumentSymbol]) -> Range {
    let start = symbols
        .first()
        .map(|symbol| symbol.range.start)
        .unwrap_or(Position::new(0, 0));
    let end = symbols
        .last()
        .map(|symbol| symbol.range.end)
        .unwrap_or(Position::new(0, 0));
    Range::new(start, end)
}

fn generated_item_origin_symbol(
    item: &macro_system::AstGeneratedItemOrigin,
    origin: &macro_system::AstMacroOrigin,
    fallback_range: Range,
) -> DocumentSymbol {
    let range = item.span.as_ref().map(span_range).unwrap_or(fallback_range);
    let children = item
        .generated_member_origins
        .iter()
        .map(|member| generated_member_origin_symbol(member, origin, range))
        .collect::<Vec<_>>();
    DocumentSymbol {
        name: item.label.to_string(),
        detail: Some(format!("generated by {} {}", origin.kind.as_str(), origin.macro_name)),
        kind: generated_item_symbol_kind(&item.label),
        tags: None,
        #[allow(deprecated)]
        deprecated: None,
        range,
        selection_range: range,
        children: (!children.is_empty()).then_some(children),
    }
}

fn fallback_generated_item_origin_symbol(
    label: &str,
    origin: &macro_system::AstMacroOrigin,
    fallback_range: Range,
) -> DocumentSymbol {
    DocumentSymbol {
        name: label.to_string(),
        detail: Some(format!("generated by {} {}", origin.kind.as_str(), origin.macro_name)),
        kind: generated_item_symbol_kind(label),
        tags: None,
        #[allow(deprecated)]
        deprecated: None,
        range: fallback_range,
        selection_range: fallback_range,
        children: None,
    }
}

fn generated_member_origin_symbol(
    member: &macro_system::AstGeneratedMemberOrigin,
    origin: &macro_system::AstMacroOrigin,
    fallback_range: Range,
) -> DocumentSymbol {
    let range = member.span.as_ref().map(span_range).unwrap_or(fallback_range);
    DocumentSymbol {
        name: member.label.to_string(),
        detail: Some(format!("generated by {} {}", origin.kind.as_str(), origin.macro_name)),
        kind: generated_member_symbol_kind(&member.label),
        tags: None,
        #[allow(deprecated)]
        deprecated: None,
        range,
        selection_range: range,
        children: None,
    }
}

fn span_range(span: &Span) -> Range {
    Range::new(
        Position::new(span.start.line - 1, span.start.column.saturating_sub(1)),
        Position::new(span.end.line - 1, span.end.column.saturating_sub(1)),
    )
}

fn generated_item_symbol_kind(label: &str) -> SymbolKind {
    if label.starts_with("fn ") {
        SymbolKind::FUNCTION
    } else if label.starts_with("struct ") {
        SymbolKind::STRUCT
    } else if label.starts_with("trait ") {
        SymbolKind::INTERFACE
    } else if label.starts_with("type ") {
        SymbolKind::TYPE_PARAMETER
    } else {
        SymbolKind::OBJECT
    }
}

fn generated_member_symbol_kind(label: &str) -> SymbolKind {
    if label.starts_with("fn ") {
        SymbolKind::METHOD
    } else if label.starts_with("expr self.") {
        SymbolKind::FIELD
    } else if label.starts_with("call ") {
        SymbolKind::FUNCTION
    } else if label.starts_with("literal ") {
        SymbolKind::CONSTANT
    } else if label.starts_with("binding ")
        || label.starts_with("ref ")
        || label.starts_with("assign_ref ")
        || label.starts_with("compound_assign_ref ")
    {
        SymbolKind::VARIABLE
    } else if label.starts_with("struct_field ") {
        SymbolKind::FIELD
    } else if label.starts_with("map_key ") || label.starts_with("named_arg ") || label.starts_with("named_param_type ")
    {
        SymbolKind::PROPERTY
    } else if label.starts_with("type_ref ") || label.starts_with("type_var ") || label.starts_with("type_expr ") {
        SymbolKind::TYPE_PARAMETER
    } else if label.starts_with("import_file ") {
        SymbolKind::FILE
    } else if label.starts_with("import_module ") || label.starts_with("import_namespace ") {
        SymbolKind::MODULE
    } else if label.starts_with("import_item ") || label.starts_with("import_alias ") {
        SymbolKind::VARIABLE
    } else if label.starts_with("attr ")
        || label.starts_with("attr_arg ")
        || label.starts_with("attr_key ")
        || label.starts_with("attr_value ")
    {
        SymbolKind::PROPERTY
    } else if label.starts_with("derive ") {
        SymbolKind::ENUM_MEMBER
    } else if label.starts_with("stmt ")
        || label.starts_with("select ")
        || label.starts_with("match ")
        || label.starts_with("pattern ")
        || label.starts_with("for_pattern ")
        || label.starts_with("template_part ")
        || label.starts_with("range ")
        || label == "match_arm"
    {
        SymbolKind::EVENT
    } else if label.starts_with("index ") {
        SymbolKind::ARRAY
    } else if label.starts_with("expr ")
        || label.starts_with("binary ")
        || label.starts_with("unary ")
        || label.starts_with("compound_assign ")
    {
        SymbolKind::OPERATOR
    } else {
        SymbolKind::OBJECT
    }
}
